### ISSUE TITLE
Restructure Languages to account for Node.js

### ISSUE THREAD

**Issue by adamkelsall** [newcastle-digital/docs#44]
While getting links ready to add to the Node.js page, I've realised a problem:

- Node.js is not a framework, it's platform / runtime environment.
- Express is a framework (no issues here).
- There's a multitude of npms (and npm itself) that could have their own pages providing there's enough content.

So the question is, do we need to restructure the top-level of *docs* to accommodate for new content?

**Comment by adamkelsall** [comment]
Suggestion:

- Frameworks
  - React / Angular / D3 / Vue.js etc.
  - Express
- Languages
  - CSS
    - Sass
  - HTML
    - Pug
  - JavaScript
    - Node.js

**Comment by adamk5550** [comment]
How about separating into front end and backend instead?

**Comment by adamkelsall** [comment]
At which point?

**Comment by adamk5550** [comment]
Top Level?

#Frontend
- JavaScript
    - React / Angular / D3 / Vue.js etc.
- CSS
   - Sass
- HTML
    - Pug

#Backend
- Node.js
    - Express

- PHP
    - Laravel

**Comment by adamkelsall** [comment]
That looks reasonable. There's the whole "technically JavaScript is both" but I think having Node.js under backend covers that off nicely.

Only remaining points/concerns:

- Does this mean we're excluding the possibility of having native app development info (Java/Objective C/Swift) on here or does it fit? Do we care?
- Where does *Tools* fit under this? Alongside Frontend/Backend?

**Comment by adamk5550** [comment]
# Languages 
   ## Frontend Web
   ## Backend Web
   ## Java
   ## C 

# Tooling


^ this could work although we may need to be careful about adding too many layers and Tooling may have to be moved around to fit the Language ?

**Comment by adamkelsall** [comment]
I like the idea of splitting non-language stuff out into its own section (of sorts), that could work. *Tooling* at the moment doesn't have much in it, but if I think about what I'd like it to contain: linting, IDEs & plugins, Agile, Git, development practices (in general), there's a lot of stuff that's got nothing to do with languages.

I think for now if we just have *Frontend* and *Backend*, if anyone wants to add non-web languages we'll figure it out. It's 100% us at the moment, so I don't see it being a big deal any time soon.

**Comment by adamkelsall** [comment]
Closed by #45
